import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import Link from 'next/link'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <h1>Pagina idiomas</h1>
        <nav >
          <ul className= "flex gap-2">
            <li><Link href="/">Home</Link></li>
            <li><Link href="/users">Sobre</Link></li>
            <li><Link href="/news">Notícias</Link></li>
            <li><Link href="projects">Projetos</Link></li>
            <li><Link href="contact">Contato</Link></li>
          </ul>
        </nav>
        <hr />
        {children}</body>
    </html>
  )
}
